In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('Reviews.csv')

In [8]:

print(df.columns.tolist())

['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text']

In [9]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [10]:
df = df[['Score', 'Text']]

In [11]:
df = df[df['Score'] !=3]
df['Sentiment'] = df['Score'].apply(lambda x: 1 if x >= 4 else 0)

In [12]:
df = df.drop(columns=['Score'])

In [13]:
print(df.shape)

(525814, 2)

In [14]:
df.head

<bound method NDFrame.head of                                                      Text  Sentiment
0       I have bought several of the Vitality canned d...          1
1       Product arrived labeled as Jumbo Salted Peanut...          0
2       This is a confection that has been around a fe...          1
3       If you are looking for the secret ingredient i...          0
4       Great taffy at a great price.  There was a wid...          1
...                                                   ...        ...
568449  Great for sesame chicken..this is a good if no...          1
568450  I'm disappointed with the flavor. The chocolat...          0
568451  These stars are small, so you can give 10-15 o...          1
568452  These are the BEST treats for training and rew...          1
568453  I am very satisfied ,product is as advertised,...          1

[525814 rows x 2 columns]>

In [15]:
df = df.sample(n=10000, random_state=42) #use only 10k row

In [16]:
df = df.reset_index(drop=True)

In [17]:
print(df.shape)

(10000, 2)

In [18]:
print(df['Sentiment'].value_counts())

Sentiment
1    8453
0    1547
Name: count, dtype: int64

In [19]:
df.head()

                                                Text  Sentiment
0  This is a very high quality dog food with meat...          1
1  I love this cake mix and the other 3 mixes as ...          1
2  A nice strong brew. I am new to Keurig and hav...          1
3  I just found PB2 and PB2 with chocolate and I ...          1
4  Delightful mint tea as one would expect. Note ...          1